Repository C-Super/appY-Documentation, pull requests merged in 2024-03, with the labels that each got.

#26 Entretient Qualitatif Danita
  Calendrier/2024-04-19 Rossiny- pas la ( opération coude).md
  Étude de marché/Questionnaire/Qualitatif - Danita Mboti.md
Labels: documentation, pré-projet, enhancement, Review effort [1-5]: 2

#37 Analyse des reponses qualitatif
  Étude de marché/Questionnaire/Qualitatif/Analyse Qualitatif.md
  Étude de marché/Questionnaire/Qualitatif/Qualitatif - Cecilia.md
  Étude de marché/Questionnaire/Qualitatif/Qualitatif - Danita Mboti.md
  Étude de marché/Questionnaire/Qualitatif/Qualitatif - Louis Beltrami.md
  Étude de marché/Questionnaire/Qualitatif/Qualitatif.md
  Étude de marché/Questionnaire/Quantitatif/Quantitatif.md
Labels: documentation, enhancement, Review effort [1-5]: 2

#34 28 rapport création doc gestion de projet
  Gestion de projet/Rapport/Introduction et mise en place.md
  Gestion de projet/Rapport/Introduction.md
  img/Gestion de projet/organisationHebdomadaire.jpg
  img/Gestion de projet/repartitionEquipes.jpg
Labels: documentation, Review effort [1-5]: 2

#38 add userStories file to documentation
  Gestion de projet/User stories.md
Labels: Review effort [1-5]: 1, enhancement

#50 Commit pour exemple
  README.md
Labels: documentation, Review effort [1-5]: 1

#27 Persona
  Calendrier/2024-03-25 Marine partie en quête de l'enfant malade.md
  b2b/Commerçants - 1er contact.md
  b2b/Lettre d'intention.md
Labels: documentation, enhancement, Review effort [1-5]: 2

#25 create questions
  benchmark/Interview Alison Totemi.md
Labels: documentation, Review effort [1-5]: 1
