Repository C-Super/appY-Documentation, pull requests merged in 2024-04, with the labels that each got.

#79 Ajout de l'analyse de l'étude quantitatif
  img/Étude de marché/statQuanti.png
  Étude de marché/Questionnaire/Quantitatif/Quantitatif.md
Labels: documentation, Review effort [1-5]: 1

#97 89 uiux rapport recherches
  .obsidian/community-plugins.json
  .obsidian/plugins/image-captions/main.js
  .obsidian/plugins/image-captions/manifest.json
  .obsidian/plugins/image-captions/styles.css
  img/ux/ux_empathy_map_1.png
  img/ux/ux_empathy_map_2.png
  img/ux/ux_empathy_map_3.png
  img/ux/ux_empathy_map_4.png
  img/ux/ux_modele_de_representation.png
  img/ux/ux_musthave.png
  img/ux/ux_persona_1.png
  img/ux/ux_persona_2.png
  img/ux/ux_persona_3.png
  ui-ux/Rapport.md
  ui-ux/annexes/Empathy map.md
  ui-ux/annexes/Matrice must-have.md
  ui-ux/annexes/Modèle de représentation.md
  ui-ux/annexes/Personas.md
Labels: documentation, ui/ux, enhancement, Review effort [1-5]: 3

#105 Ajout création parcours nature
  contenu/Parcours nature.md
Labels: documentation, Review effort [1-5]: 1

#122 Ajout strat
  Marketing/Stratégie globale.md
Labels: documentation, Review effort [1-5]: 1, enhancement

#101 Doc storytelling cadre global
  Parcours/Storytelling/Storytelling - Cadre général.md
  img/Storytelling/Courbe-suspense.png
  img/Storytelling/Structure-parcours.jpg
Labels: documentation, Review effort [1-5]: 1

#99 insertion texte ontologie / taxonomie
  ui-ux/Rapport.md
Labels: documentation, Review effort [1-5]: 1, enhancement

#131 résumé entretien téléphonique avec Aetepic
  b2b/Documentation - rapport.md
Labels: documentation, Review effort [1-5]: 1

#106 51 marketing création de parcours ville
  Parcours/ville/Postes.md
Labels: enhancement, Review effort [1-5]: 2

#133 ajout du protocole de test utilisateurs
  SEQ.png
  ui-ux/annexes/Test utilisateurs.md
Labels: documentation, Review effort [1-5]: 2

#157 83 marketing - guide de communication et templates
  Marketing/Guide pour la communication.md
  img/Marketing/GuideBus.png
  img/Marketing/GuideEvent.png
  img/Marketing/GuideMerch.png
  img/Marketing/GuidePrint.png
  img/Marketing/GuideTVRadio.png
  img/Marketing/GuideTikTok.png
  img/Marketing/GuidelineDisplay.png
Labels: documentation, Review effort [1-5]: 1

#161 139 parcours design panneaux parcours
  Parcours/Panneaux parcours.md
  img/parcours/panneau avec indice final demo.png
  img/parcours/panneau final demo.png
  img/parcours/petit panneau final demo video.png
  img/ux/SEQ.png
  ui-ux/annexes/Test utilisateurs.md
Labels: documentation, enhancement, Review effort [1-5]: 2

#162 ajout des personnages secondaires
  Parcours/Personnages secondaires.md
  img/Présentation/AdobeStock_662502869 (1) 2.png
  img/Présentation/IgorT 1.png
  img/Présentation/Juliette_V4 1.png
  img/Présentation/picatso_transparent 1.png
  img/Présentation/splashv2 1.png
Labels: enhancement, Review effort [1-5]: 2
